# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-30 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='move_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
