# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-02 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='number_increment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
